// Code generated by thriftgo (0.3.18). DO NOT EDIT.

package maintain

import (
	"context"
	"github.com/apache/thrift/lib/go/thrift"
)

type MaintainService interface {
}

type MaintainServiceClient struct {
	c thrift.TClient
}

func NewMaintainServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *MaintainServiceClient {
	return &MaintainServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewMaintainServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *MaintainServiceClient {
	return &MaintainServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewMaintainServiceClient(c thrift.TClient) *MaintainServiceClient {
	return &MaintainServiceClient{
		c: c,
	}
}

func (p *MaintainServiceClient) Client_() thrift.TClient {
	return p.c
}

type MaintainServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      MaintainService
}

func (p *MaintainServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *MaintainServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *MaintainServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewMaintainServiceProcessor(handler MaintainService) *MaintainServiceProcessor {
	self := &MaintainServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	return self
}
func (p *MaintainServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}
