// Code generated by thriftgo (0.3.18). DO NOT EDIT.

package material

import (
	"context"
	"github.com/apache/thrift/lib/go/thrift"
)

type MaterialService interface {
}

type MaterialServiceClient struct {
	c thrift.TClient
}

func NewMaterialServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *MaterialServiceClient {
	return &MaterialServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewMaterialServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *MaterialServiceClient {
	return &MaterialServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewMaterialServiceClient(c thrift.TClient) *MaterialServiceClient {
	return &MaterialServiceClient{
		c: c,
	}
}

func (p *MaterialServiceClient) Client_() thrift.TClient {
	return p.c
}

type MaterialServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      MaterialService
}

func (p *MaterialServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *MaterialServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *MaterialServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewMaterialServiceProcessor(handler MaterialService) *MaterialServiceProcessor {
	self := &MaterialServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	return self
}
func (p *MaterialServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}
