// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	api_model "judgeMore_server/app/gateway/router/api/model"
	api_user "judgeMore_server/app/gateway/router/api/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	api_user.Register(r)

	api_model.Register(r)

}
