// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	api_appeal "judgeMore_server/app/gateway/router/api/appeal"
	api_maintain "judgeMore_server/app/gateway/router/api/maintain"
	api_material "judgeMore_server/app/gateway/router/api/material"
	api_model "judgeMore_server/app/gateway/router/api/model"
	api_score "judgeMore_server/app/gateway/router/api/score"
	api_user "judgeMore_server/app/gateway/router/api/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	api_maintain.Register(r)

	api_score.Register(r)

	api_appeal.Register(r)

	api_user.Register(r)

	api_model.Register(r)

	api_material.Register(r)
}
